In [42]:
import numpy as np
import sympy as sym
from sympy import init_printing
from math import sin, cos


In [4]:
def stress_rotation(phi, theta, rho):

    Rstress = np.asmatrix([
    [ np.cos(phi)*np.cos(theta), -2*np.sin(phi)*np.sin(rho/2)**2 + np.sin(phi) - np.sin(rho)*np.sin(theta)*np.cos(phi), np.sin(phi)*np.sin(rho) + np.sin(theta)*np.cos(phi + rho)/2 + np.sin(-phi + rho + theta)/4 + np.sin(phi - rho + theta)/4],
    [-np.sin(phi)*np.cos(theta),  np.sin(phi)*np.sin(rho)*np.sin(theta) - 2*np.sin(rho/2)**2*np.cos(phi) + np.cos(phi), np.sin(rho)*np.cos(phi) - np.sin(theta)*np.sin(phi + rho)/2 - np.cos(-phi + rho + theta)/4 + np.cos(phi - rho + theta)/4],
    [         -np.sin(theta),                                                -np.sin(rho)*np.cos(theta),                                                                                    np.cos(rho)*np.cos(theta)]])

    return Rstress

In [6]:
Rstress = stress_rotation(-np.pi/4, np.pi/2, 0)
print(Rstress)

[[  4.32978028e-17  -7.07106781e-01   7.07106781e-01]
 [  4.32978028e-17   7.07106781e-01   7.07106781e-01]
 [ -1.00000000e+00  -0.00000000e+00   6.12323400e-17]]


In [7]:
def fault_rotation(xi, delta):
    
    Rfault =  np.asmatrix([
            [ np.cos(delta)*np.cos(xi), np.sin(xi), -np.sin(delta)*np.cos(xi)],
            [-np.sin(xi)*np.cos(delta), np.cos(xi),  np.sin(delta)*np.sin(xi)],
            [         np.sin(delta),       0,          np.cos(delta)]])
    
    return Rfault

In [39]:
Rfault = fault_rotation(0, np.pi/2)
print(Rfault)

[[  6.12323400e-17   0.00000000e+00  -1.00000000e+00]
 [ -0.00000000e+00   1.00000000e+00   0.00000000e+00]
 [  1.00000000e+00   0.00000000e+00   6.12323400e-17]]


In [10]:
def pstress_matrix(sigma_1, sigma_2, sigma_3):
    
    pstress = np.asmatrix([[sigma_1, 0, 0], [0, sigma_2, 0], [0, 0, sigma_3]])
    
    return pstress

In [12]:
pstress = pstress_matrix(-1, -1/2, -1/4)
print(pstress)

[[-1.    0.    0.  ]
 [ 0.   -0.5   0.  ]
 [ 0.    0.   -0.25]]


In [18]:
def stress_geo(sigma_1, sigma_2, sigma_3, phi, theta, rho):
    
    stressgeo = np.asmatrix([
[                                                                                                                          sigma_1*np.cos(phi)**2*np.cos(theta)**2 + sigma_2*(-2*np.sin(phi)*np.cos(rho/2)**2 + np.sin(phi) + np.sin(rho)*np.sin(theta)*np.cos(phi))**2 + sigma_3*(np.sin(phi)*np.sin(rho) + np.sin(theta)*np.cos(phi)*np.cos(rho))**2, -sigma_1*np.sin(phi)*np.cos(phi)*np.cos(theta)**2 + sigma_2*(-2*np.sin(phi)*np.sin(rho/2)**2 + np.sin(phi) - np.sin(rho)*np.sin(theta)*np.cos(phi))*(np.sin(phi)*np.sin(rho)*np.sin(theta) - 2*np.sin(rho/2)**2*np.cos(phi) + np.cos(phi)) + sigma_3*(np.sin(phi)*np.sin(rho) + np.sin(theta)*np.cos(phi)*np.cos(rho))*(-np.sin(phi)*np.sin(theta)*np.cos(rho) + np.sin(rho)*np.cos(phi)), -sigma_1*(-np.sin(phi - 2*theta) + np.sin(phi + 2*theta))/4 - sigma_2*(-2*np.sin(phi)*np.sin(rho/2)**2 + np.sin(phi) - np.sin(rho)*np.sin(theta)*np.cos(phi))*np.sin(rho)*np.cos(theta) + sigma_3*(np.sin(phi)*np.sin(rho) + np.sin(theta)*np.cos(phi)*np.cos(rho))*np.cos(rho)*np.cos(theta)],
[-sigma_1*np.sin(phi)*np.cos(phi)*np.cos(theta)**2 + sigma_2*(-2*np.sin(phi)*np.sin(rho/2)**2 + np.sin(phi) - np.sin(rho)*np.sin(theta)*np.cos(phi))*(np.sin(phi)*np.sin(rho)*np.sin(theta) - 2*np.sin(rho/2)**2*np.cos(phi) + np.cos(phi)) + sigma_3*(np.sin(phi)*np.sin(rho) + np.sin(theta)*np.cos(phi)*np.cos(rho))*(-np.sin(phi)*np.sin(theta)*np.cos(rho) + np.sin(rho)*np.cos(phi)),                                                                                                                           sigma_1*np.sin(phi)**2*np.cos(theta)**2 + sigma_2*(np.sin(phi)*np.sin(rho)*np.sin(theta) - 2*np.sin(rho/2)**2*np.cos(phi) + np.cos(phi))**2 + sigma_3*(-np.sin(phi)*np.sin(theta)*np.cos(rho) + np.sin(rho)*np.cos(phi))**2,   sigma_1*(np.cos(phi - 2*theta) - np.cos(phi + 2*theta))/4 - sigma_2*(np.sin(phi)*np.sin(rho)*np.sin(theta) - 2*np.sin(rho/2)**2*np.cos(phi) + np.cos(phi))*np.sin(rho)*np.cos(theta) + sigma_3*(-np.sin(phi)*np.sin(theta)*np.cos(rho) + np.sin(rho)*np.cos(phi))*np.cos(rho)*np.cos(theta)],
[                                                                    -sigma_1*(-np.sin(phi - 2*theta) + np.sin(phi + 2*theta))/4 - sigma_2*(-2*np.sin(phi)*np.sin(rho/2)**2 + np.sin(phi) - np.sin(rho)*np.sin(theta)*np.cos(phi))*np.sin(rho)*np.cos(theta) + sigma_3*(np.sin(phi)*np.sin(rho) + np.sin(theta)*np.cos(phi)*np.cos(rho))*np.cos(rho)*np.cos(theta),                                                                       sigma_1*(np.cos(phi - 2*theta) - np.cos(phi + 2*theta))/4 - sigma_2*(np.sin(phi)*np.sin(rho)*np.sin(theta) - 2*np.sin(rho/2)**2*np.cos(phi) + np.cos(phi))*np.sin(rho)*np.cos(theta) + sigma_3*(-np.sin(phi)*np.sin(theta)*np.cos(rho) + np.sin(rho)*np.cos(phi))*np.cos(rho)*np.cos(theta),                                                                                                                                              sigma_1*np.sin(theta)**2 + sigma_2*np.sin(rho)**2*np.cos(theta)**2 + sigma_3*np.cos(rho)**2*np.cos(theta)**2]])
    
    return stressgeo

In [19]:
sigma_1, sigma_2, sigma_3, phi, theta, rho = -1, -1/2, -1/4,-np.pi/4, np.pi/2, 0

In [21]:
stressgeo = stress_geo(sigma_1, sigma_2, sigma_3, phi, theta, rho)
print(stressgeo)

[[ -3.75000000e-01   1.25000000e-01   1.69311249e-17]
 [  1.25000000e-01  -3.75000000e-01   4.46867005e-17]
 [  1.69311249e-17   4.46867005e-17  -1.00000000e+00]]


In [29]:
stressgeo_check = Rstress*pstress*Rstress.T
print(stressgeo)
print(stressgeo_check)

[[ -3.75000000e-01   1.25000000e-01   1.69311249e-17]
 [  1.25000000e-01  -3.75000000e-01   4.46867005e-17]
 [  1.69311249e-17   4.46867005e-17  -1.00000000e+00]]
[[ -3.75000000e-01   1.25000000e-01   3.24733521e-17]
 [  1.25000000e-01  -3.75000000e-01   3.24733521e-17]
 [  3.24733521e-17   3.24733521e-17  -1.00000000e+00]]


In [37]:
xi, delta = 0, np.pi/2

In [41]:
stressfault = Rfault*stressgeo*Rfault.T
print(stressfault)

[[ -1.00000000e+00  -3.70326580e-17   2.13390876e-17]
 [ -3.70326580e-17  -3.75000000e-01   1.25000000e-01]
 [  2.13390876e-17   1.25000000e-01  -3.75000000e-01]]


In [44]:
def stress_fault(sigma_1, sigma_2, sigma_3, phi, theta, rho, xi, delta):
    
    sf = np.asmatrix([
[(-(-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(delta)*cos(xi) + (sigma_1*cos(phi)**2*cos(theta)**2 + sigma_2*(-2*sin(phi)*cos(rho/2)**2 + sin(phi) + sin(rho)*sin(theta)*cos(phi))**2 + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))**2)*cos(delta)*cos(xi) + (-sigma_1*sin(phi)*cos(phi)*cos(theta)**2 + sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi)) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi)))*sin(xi))*cos(delta)*cos(xi) - ((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*cos(delta)*cos(xi) + (sigma_1*(cos(phi - 2*theta) - cos(phi + 2*theta))/4 - sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))*sin(rho)*cos(theta) + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))*cos(rho)*cos(theta))*sin(xi) - (sigma_1*sin(theta)**2 + sigma_2*sin(rho)**2*cos(theta)**2 + sigma_3*cos(rho)**2*cos(theta)**2)*sin(delta)*cos(xi))*sin(delta)*cos(xi) + (-(sigma_1*(cos(phi - 2*theta) - cos(phi + 2*theta))/4 - sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))*sin(rho)*cos(theta) + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))*cos(rho)*cos(theta))*sin(delta)*cos(xi) + (sigma_1*sin(phi)**2*cos(theta)**2 + sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))**2 + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))**2)*sin(xi) + (-sigma_1*sin(phi)*cos(phi)*cos(theta)**2 + sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi)) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi)))*cos(delta)*cos(xi))*sin(xi), -(-(-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(delta)*cos(xi) + (sigma_1*cos(phi)**2*cos(theta)**2 + sigma_2*(-2*sin(phi)*cos(rho/2)**2 + sin(phi) + sin(rho)*sin(theta)*cos(phi))**2 + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))**2)*cos(delta)*cos(xi) + (-sigma_1*sin(phi)*cos(phi)*cos(theta)**2 + sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi)) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi)))*sin(xi))*sin(xi)*cos(delta) + ((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*cos(delta)*cos(xi) + (sigma_1*(cos(phi - 2*theta) - cos(phi + 2*theta))/4 - sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))*sin(rho)*cos(theta) + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))*cos(rho)*cos(theta))*sin(xi) - (sigma_1*sin(theta)**2 + sigma_2*sin(rho)**2*cos(theta)**2 + sigma_3*cos(rho)**2*cos(theta)**2)*sin(delta)*cos(xi))*sin(delta)*sin(xi) + (-(sigma_1*(cos(phi - 2*theta) - cos(phi + 2*theta))/4 - sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))*sin(rho)*cos(theta) + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))*cos(rho)*cos(theta))*sin(delta)*cos(xi) + (sigma_1*sin(phi)**2*cos(theta)**2 + sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))**2 + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))**2)*sin(xi) + (-sigma_1*sin(phi)*cos(phi)*cos(theta)**2 + sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi)) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi)))*cos(delta)*cos(xi))*cos(xi), (-(-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(delta)*cos(xi) + (sigma_1*cos(phi)**2*cos(theta)**2 + sigma_2*(-2*sin(phi)*cos(rho/2)**2 + sin(phi) + sin(rho)*sin(theta)*cos(phi))**2 + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))**2)*cos(delta)*cos(xi) + (-sigma_1*sin(phi)*cos(phi)*cos(theta)**2 + sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi)) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi)))*sin(xi))*sin(delta) + ((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*cos(delta)*cos(xi) + (sigma_1*(cos(phi - 2*theta) - cos(phi + 2*theta))/4 - sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))*sin(rho)*cos(theta) + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))*cos(rho)*cos(theta))*sin(xi) - (sigma_1*sin(theta)**2 + sigma_2*sin(rho)**2*cos(theta)**2 + sigma_3*cos(rho)**2*cos(theta)**2)*sin(delta)*cos(xi))*cos(delta)],
[ ((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(delta)*sin(xi) - (sigma_1*cos(phi)**2*cos(theta)**2 + sigma_2*(-2*sin(phi)*cos(rho/2)**2 + sin(phi) + sin(rho)*sin(theta)*cos(phi))**2 + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))**2)*sin(xi)*cos(delta) + (-sigma_1*sin(phi)*cos(phi)*cos(theta)**2 + sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi)) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi)))*cos(xi))*cos(delta)*cos(xi) - (-(-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(xi)*cos(delta) + (sigma_1*(cos(phi - 2*theta) - cos(phi + 2*theta))/4 - sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))*sin(rho)*cos(theta) + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))*cos(rho)*cos(theta))*cos(xi) + (sigma_1*sin(theta)**2 + sigma_2*sin(rho)**2*cos(theta)**2 + sigma_3*cos(rho)**2*cos(theta)**2)*sin(delta)*sin(xi))*sin(delta)*cos(xi) + ((sigma_1*(cos(phi - 2*theta) - cos(phi + 2*theta))/4 - sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))*sin(rho)*cos(theta) + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))*cos(rho)*cos(theta))*sin(delta)*sin(xi) + (sigma_1*sin(phi)**2*cos(theta)**2 + sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))**2 + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))**2)*cos(xi) - (-sigma_1*sin(phi)*cos(phi)*cos(theta)**2 + sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi)) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi)))*sin(xi)*cos(delta))*sin(xi),  -((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(delta)*sin(xi) - (sigma_1*cos(phi)**2*cos(theta)**2 + sigma_2*(-2*sin(phi)*cos(rho/2)**2 + sin(phi) + sin(rho)*sin(theta)*cos(phi))**2 + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))**2)*sin(xi)*cos(delta) + (-sigma_1*sin(phi)*cos(phi)*cos(theta)**2 + sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi)) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi)))*cos(xi))*sin(xi)*cos(delta) + (-(-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(xi)*cos(delta) + (sigma_1*(cos(phi - 2*theta) - cos(phi + 2*theta))/4 - sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))*sin(rho)*cos(theta) + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))*cos(rho)*cos(theta))*cos(xi) + (sigma_1*sin(theta)**2 + sigma_2*sin(rho)**2*cos(theta)**2 + sigma_3*cos(rho)**2*cos(theta)**2)*sin(delta)*sin(xi))*sin(delta)*sin(xi) + ((sigma_1*(cos(phi - 2*theta) - cos(phi + 2*theta))/4 - sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))*sin(rho)*cos(theta) + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))*cos(rho)*cos(theta))*sin(delta)*sin(xi) + (sigma_1*sin(phi)**2*cos(theta)**2 + sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))**2 + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))**2)*cos(xi) - (-sigma_1*sin(phi)*cos(phi)*cos(theta)**2 + sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi)) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi)))*sin(xi)*cos(delta))*cos(xi), ((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(delta)*sin(xi) - (sigma_1*cos(phi)**2*cos(theta)**2 + sigma_2*(-2*sin(phi)*cos(rho/2)**2 + sin(phi) + sin(rho)*sin(theta)*cos(phi))**2 + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))**2)*sin(xi)*cos(delta) + (-sigma_1*sin(phi)*cos(phi)*cos(theta)**2 + sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi)) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi)))*cos(xi))*sin(delta) + (-(-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(xi)*cos(delta) + (sigma_1*(cos(phi - 2*theta) - cos(phi + 2*theta))/4 - sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))*sin(rho)*cos(theta) + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))*cos(rho)*cos(theta))*cos(xi) + (sigma_1*sin(theta)**2 + sigma_2*sin(rho)**2*cos(theta)**2 + sigma_3*cos(rho)**2*cos(theta)**2)*sin(delta)*sin(xi))*cos(delta)],
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  -((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(delta) + (sigma_1*sin(theta)**2 + sigma_2*sin(rho)**2*cos(theta)**2 + sigma_3*cos(rho)**2*cos(theta)**2)*cos(delta))*sin(delta)*cos(xi) + ((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*cos(delta) + (sigma_1*cos(phi)**2*cos(theta)**2 + sigma_2*(-2*sin(phi)*cos(rho/2)**2 + sin(phi) + sin(rho)*sin(theta)*cos(phi))**2 + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))**2)*sin(delta))*cos(delta)*cos(xi) + ((sigma_1*(cos(phi - 2*theta) - cos(phi + 2*theta))/4 - sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))*sin(rho)*cos(theta) + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))*cos(rho)*cos(theta))*cos(delta) + (-sigma_1*sin(phi)*cos(phi)*cos(theta)**2 + sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi)) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi)))*sin(delta))*sin(xi),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(delta) + (sigma_1*sin(theta)**2 + sigma_2*sin(rho)**2*cos(theta)**2 + sigma_3*cos(rho)**2*cos(theta)**2)*cos(delta))*sin(delta)*sin(xi) - ((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*cos(delta) + (sigma_1*cos(phi)**2*cos(theta)**2 + sigma_2*(-2*sin(phi)*cos(rho/2)**2 + sin(phi) + sin(rho)*sin(theta)*cos(phi))**2 + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))**2)*sin(delta))*sin(xi)*cos(delta) + ((sigma_1*(cos(phi - 2*theta) - cos(phi + 2*theta))/4 - sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))*sin(rho)*cos(theta) + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))*cos(rho)*cos(theta))*cos(delta) + (-sigma_1*sin(phi)*cos(phi)*cos(theta)**2 + sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi)) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi)))*sin(delta))*cos(xi),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(delta) + (sigma_1*sin(theta)**2 + sigma_2*sin(rho)**2*cos(theta)**2 + sigma_3*cos(rho)**2*cos(theta)**2)*cos(delta))*cos(delta) + ((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*cos(delta) + (sigma_1*cos(phi)**2*cos(theta)**2 + sigma_2*(-2*sin(phi)*cos(rho/2)**2 + sin(phi) + sin(rho)*sin(theta)*cos(phi))**2 + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))**2)*sin(delta))*sin(delta)]])
    
    return sf

In [46]:
stressfault = stress_fault(sigma_1, sigma_2, sigma_3, phi, theta, rho, xi, delta)
print(stressfault)

[[ -1.00000000e+00  -3.70326580e-17   2.13390876e-17]
 [ -3.70326580e-17  -3.75000000e-01   1.25000000e-01]
 [  2.13390876e-17   1.25000000e-01  -3.75000000e-01]]


In [47]:
def taudip(sigma_1, sigma_2, sigma_3, phi, theta, rho, xi, delta):
    
    tdip = -((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(delta)*sin(xi) - (sigma_1*cos(phi)**2*cos(theta)**2 + sigma_2*(-2*sin(phi)*cos(rho/2)**2 + sin(phi) + sin(rho)*sin(theta)*cos(phi))**2 + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))**2)*sin(xi)*cos(delta) + (-sigma_1*sin(phi)*cos(phi)*cos(theta)**2 + sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi)) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi)))*cos(xi))*sin(delta) - (-(-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(xi)*cos(delta) + (sigma_1*(cos(phi - 2*theta) - cos(phi + 2*theta))/4 - sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))*sin(rho)*cos(theta) + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))*cos(rho)*cos(theta))*cos(xi) + (sigma_1*sin(theta)**2 + sigma_2*sin(rho)**2*cos(theta)**2 + sigma_3*cos(rho)**2*cos(theta)**2)*sin(delta)*sin(xi))*cos(delta)
    
    return tdip

In [48]:
def taustrike(sigma_1, sigma_2, sigma_3, phi, theta, rho, xi, delta):

    
    ts = (-(-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(delta)*cos(xi) + (sigma_1*cos(phi)**2*cos(theta)**2 + sigma_2*(-2*sin(phi)*cos(rho/2)**2 + sin(phi) + sin(rho)*sin(theta)*cos(phi))**2 + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))**2)*cos(delta)*cos(xi) + (-sigma_1*sin(phi)*cos(phi)*cos(theta)**2 + sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi)) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi)))*sin(xi))*sin(delta) + ((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*cos(delta)*cos(xi) + (sigma_1*(cos(phi - 2*theta) - cos(phi + 2*theta))/4 - sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))*sin(rho)*cos(theta) + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))*cos(rho)*cos(theta))*sin(xi) - (sigma_1*sin(theta)**2 + sigma_2*sin(rho)**2*cos(theta)**2 + sigma_3*cos(rho)**2*cos(theta)**2)*sin(delta)*cos(xi))*cos(delta)
    
    return ts

In [50]:
tdip, tstrike = taudip(sigma_1, sigma_2, sigma_3, phi, theta, rho, xi, delta), taustrike(sigma_1, sigma_2, sigma_3, phi, theta, rho, xi, delta)

In [52]:
print(tdip)
print(tstrike)

-0.125
2.1339087560669545e-17


In [70]:
rake = np.arctan(tstrike/tdip)
print(rake)

-1.70712700485e-16


In [66]:
def pred_rake(sigma_1, sigma_2, sigma_3, phi, theta, rho, xi, delta):
    
    rake = -np.arctan(-(-((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(delta)*sin(xi) - (sigma_1*cos(phi)**2*cos(theta)**2 + sigma_2*(-2*sin(phi)*cos(rho/2)**2 + sin(phi) + sin(rho)*sin(theta)*cos(phi))**2 + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))**2)*sin(xi)*cos(delta) + (-sigma_1*sin(phi)*cos(phi)*cos(theta)**2 + sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi)) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi)))*cos(xi))*sin(delta) - (-(-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(xi)*cos(delta) + (sigma_1*(cos(phi - 2*theta) - cos(phi + 2*theta))/4 - sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))*sin(rho)*cos(theta) + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))*cos(rho)*cos(theta))*cos(xi) + (sigma_1*sin(theta)**2 + sigma_2*sin(rho)**2*cos(theta)**2 + sigma_3*cos(rho)**2*cos(theta)**2)*sin(delta)*sin(xi))*cos(delta))/((-(-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(delta)*cos(xi) + (sigma_1*cos(phi)**2*cos(theta)**2 + sigma_2*(-2*sin(phi)*cos(rho/2)**2 + sin(phi) + sin(rho)*sin(theta)*cos(phi))**2 + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))**2)*cos(delta)*cos(xi) + (-sigma_1*sin(phi)*cos(phi)*cos(theta)**2 + sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi)) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi)))*sin(xi))*sin(delta) + ((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*cos(delta)*cos(xi) + (sigma_1*(cos(phi - 2*theta) - cos(phi + 2*theta))/4 - sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))*sin(rho)*cos(theta) + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))*cos(rho)*cos(theta))*sin(xi) - (sigma_1*sin(theta)**2 + sigma_2*sin(rho)**2*cos(theta)**2 + sigma_3*cos(rho)**2*cos(theta)**2)*sin(delta)*cos(xi))*cos(delta)))
    
    return rake
    

In [71]:
def drakedphi(sigma_1, sigma_2, sigma_3, phi, theta, rho, xi, delta):
    
    dldd = (-((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(delta)*sin(xi) - (sigma_1*cos(phi)**2*cos(theta)**2 + sigma_2*(-2*sin(phi)*cos(rho/2)**2 + sin(phi) + sin(rho)*sin(theta)*cos(phi))**2 + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))**2)*sin(xi)*cos(delta) + (-sigma_1*sin(phi)*cos(phi)*cos(theta)**2 + sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi)) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi)))*cos(xi))*sin(delta) - (-(-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(xi)*cos(delta) + (sigma_1*(cos(phi - 2*theta) - cos(phi + 2*theta))/4 - sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))*sin(rho)*cos(theta) + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))*cos(rho)*cos(theta))*cos(xi) + (sigma_1*sin(theta)**2 + sigma_2*sin(rho)**2*cos(theta)**2 + sigma_3*cos(rho)**2*cos(theta)**2)*sin(delta)*sin(xi))*cos(delta))*((-(-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(delta)*cos(xi) - (sigma_1*sin(theta)**2 + sigma_2*sin(rho)**2*cos(theta)**2 + sigma_3*cos(rho)**2*cos(theta)**2)*cos(delta)*cos(xi))*cos(delta) + (-(-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*cos(delta)*cos(xi) - (sigma_1*cos(phi)**2*cos(theta)**2 + sigma_2*(-2*sin(phi)*cos(rho/2)**2 + sin(phi) + sin(rho)*sin(theta)*cos(phi))**2 + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))**2)*sin(delta)*cos(xi))*sin(delta) + (-(-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(delta)*cos(xi) + (sigma_1*cos(phi)**2*cos(theta)**2 + sigma_2*(-2*sin(phi)*cos(rho/2)**2 + sin(phi) + sin(rho)*sin(theta)*cos(phi))**2 + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))**2)*cos(delta)*cos(xi) + (-sigma_1*sin(phi)*cos(phi)*cos(theta)**2 + sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi)) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi)))*sin(xi))*cos(delta) - ((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*cos(delta)*cos(xi) + (sigma_1*(cos(phi - 2*theta) - cos(phi + 2*theta))/4 - sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))*sin(rho)*cos(theta) + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))*cos(rho)*cos(theta))*sin(xi) - (sigma_1*sin(theta)**2 + sigma_2*sin(rho)**2*cos(theta)**2 + sigma_3*cos(rho)**2*cos(theta)**2)*sin(delta)*cos(xi))*sin(delta))/((-((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(delta)*sin(xi) - (sigma_1*cos(phi)**2*cos(theta)**2 + sigma_2*(-2*sin(phi)*cos(rho/2)**2 + sin(phi) + sin(rho)*sin(theta)*cos(phi))**2 + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))**2)*sin(xi)*cos(delta) + (-sigma_1*sin(phi)*cos(phi)*cos(theta)**2 + sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi)) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi)))*cos(xi))*sin(delta) - (-(-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(xi)*cos(delta) + (sigma_1*(cos(phi - 2*theta) - cos(phi + 2*theta))/4 - sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))*sin(rho)*cos(theta) + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))*cos(rho)*cos(theta))*cos(xi) + (sigma_1*sin(theta)**2 + sigma_2*sin(rho)**2*cos(theta)**2 + sigma_3*cos(rho)**2*cos(theta)**2)*sin(delta)*sin(xi))*cos(delta))**2 + ((-(-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(delta)*cos(xi) + (sigma_1*cos(phi)**2*cos(theta)**2 + sigma_2*(-2*sin(phi)*cos(rho/2)**2 + sin(phi) + sin(rho)*sin(theta)*cos(phi))**2 + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))**2)*cos(delta)*cos(xi) + (-sigma_1*sin(phi)*cos(phi)*cos(theta)**2 + sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi)) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi)))*sin(xi))*sin(delta) + ((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*cos(delta)*cos(xi) + (sigma_1*(cos(phi - 2*theta) - cos(phi + 2*theta))/4 - sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))*sin(rho)*cos(theta) + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))*cos(rho)*cos(theta))*sin(xi) - (sigma_1*sin(theta)**2 + sigma_2*sin(rho)**2*cos(theta)**2 + sigma_3*cos(rho)**2*cos(theta)**2)*sin(delta)*cos(xi))*cos(delta))**2) + (-(-(-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(delta)*cos(xi) + (sigma_1*cos(phi)**2*cos(theta)**2 + sigma_2*(-2*sin(phi)*cos(rho/2)**2 + sin(phi) + sin(rho)*sin(theta)*cos(phi))**2 + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))**2)*cos(delta)*cos(xi) + (-sigma_1*sin(phi)*cos(phi)*cos(theta)**2 + sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi)) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi)))*sin(xi))*sin(delta) - ((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*cos(delta)*cos(xi) + (sigma_1*(cos(phi - 2*theta) - cos(phi + 2*theta))/4 - sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))*sin(rho)*cos(theta) + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))*cos(rho)*cos(theta))*sin(xi) - (sigma_1*sin(theta)**2 + sigma_2*sin(rho)**2*cos(theta)**2 + sigma_3*cos(rho)**2*cos(theta)**2)*sin(delta)*cos(xi))*cos(delta))*(-((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(delta)*sin(xi) + (sigma_1*sin(theta)**2 + sigma_2*sin(rho)**2*cos(theta)**2 + sigma_3*cos(rho)**2*cos(theta)**2)*sin(xi)*cos(delta))*cos(delta) - ((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(xi)*cos(delta) + (sigma_1*cos(phi)**2*cos(theta)**2 + sigma_2*(-2*sin(phi)*cos(rho/2)**2 + sin(phi) + sin(rho)*sin(theta)*cos(phi))**2 + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))**2)*sin(delta)*sin(xi))*sin(delta) - ((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(delta)*sin(xi) - (sigma_1*cos(phi)**2*cos(theta)**2 + sigma_2*(-2*sin(phi)*cos(rho/2)**2 + sin(phi) + sin(rho)*sin(theta)*cos(phi))**2 + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))**2)*sin(xi)*cos(delta) + (-sigma_1*sin(phi)*cos(phi)*cos(theta)**2 + sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi)) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi)))*cos(xi))*cos(delta) + (-(-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(xi)*cos(delta) + (sigma_1*(cos(phi - 2*theta) - cos(phi + 2*theta))/4 - sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))*sin(rho)*cos(theta) + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))*cos(rho)*cos(theta))*cos(xi) + (sigma_1*sin(theta)**2 + sigma_2*sin(rho)**2*cos(theta)**2 + sigma_3*cos(rho)**2*cos(theta)**2)*sin(delta)*sin(xi))*sin(delta))/((-((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(delta)*sin(xi) - (sigma_1*cos(phi)**2*cos(theta)**2 + sigma_2*(-2*sin(phi)*cos(rho/2)**2 + sin(phi) + sin(rho)*sin(theta)*cos(phi))**2 + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))**2)*sin(xi)*cos(delta) + (-sigma_1*sin(phi)*cos(phi)*cos(theta)**2 + sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi)) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi)))*cos(xi))*sin(delta) - (-(-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(xi)*cos(delta) + (sigma_1*(cos(phi - 2*theta) - cos(phi + 2*theta))/4 - sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))*sin(rho)*cos(theta) + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))*cos(rho)*cos(theta))*cos(xi) + (sigma_1*sin(theta)**2 + sigma_2*sin(rho)**2*cos(theta)**2 + sigma_3*cos(rho)**2*cos(theta)**2)*sin(delta)*sin(xi))*cos(delta))**2 + ((-(-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*sin(delta)*cos(xi) + (sigma_1*cos(phi)**2*cos(theta)**2 + sigma_2*(-2*sin(phi)*cos(rho/2)**2 + sin(phi) + sin(rho)*sin(theta)*cos(phi))**2 + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))**2)*cos(delta)*cos(xi) + (-sigma_1*sin(phi)*cos(phi)*cos(theta)**2 + sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi)) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi)))*sin(xi))*sin(delta) + ((-sigma_1*(-sin(phi - 2*theta) + sin(phi + 2*theta))/4 - sigma_2*(-2*sin(phi)*sin(rho/2)**2 + sin(phi) - sin(rho)*sin(theta)*cos(phi))*sin(rho)*cos(theta) + sigma_3*(sin(phi)*sin(rho) + sin(theta)*cos(phi)*cos(rho))*cos(rho)*cos(theta))*cos(delta)*cos(xi) + (sigma_1*(cos(phi - 2*theta) - cos(phi + 2*theta))/4 - sigma_2*(sin(phi)*sin(rho)*sin(theta) - 2*sin(rho/2)**2*cos(phi) + cos(phi))*sin(rho)*cos(theta) + sigma_3*(-sin(phi)*sin(theta)*cos(rho) + sin(rho)*cos(phi))*cos(rho)*cos(theta))*sin(xi) - (sigma_1*sin(theta)**2 + sigma_2*sin(rho)**2*cos(theta)**2 + sigma_3*cos(rho)**2*cos(theta)**2)*sin(delta)*cos(xi))*cos(delta))**2)
    
    return dldd

In [73]:
deriv = drakedphi(sigma_1, sigma_2, sigma_3, phi, theta, rho, xi, delta)
print(deriv)

5.0


In [81]:
prop_err = np.sqrt((deriv*(10*np.pi/180))**2)
print(prop_err*180/np.pi)

50.0
